num1 = int(float(input("Enter First Number :")))
num2 = int(float(input("Enter Second Number :")))
addition = int(float(num1 + num2))
print("The Addition is :",addition)
subtraction = int(float((num1-num2))) 
print("The Subtraction is :",subtraction)
multiplication = int(float(num1 * num2))
print("The Multiplication is :",multiplication)
division = int(float(num1 / num2))
print("The Division is :",division)
modulus = int(float(num1 % num2))
print("The Modulus is :",modulus)